### ISSUE TITLE
Erro de digitação nas páginas das tabelas dos datasets BD+

### ISSUE THREAD

**Issue by vmussa** [basedosdados/website#10]
Olá, todo mundo. Não sei se é o local ideal para reportar esse erro e não conheço a estrutura do CKAN para fazer a correção.

#### Descrição do erro
Em todas as páginas que eu visitei de tabelas de datatasets BD+, a primeira frase, que apresenta a tabela, tem um erro de digitação:
> Nós _tratamentos_ e disponibilizamos esta tabela no nosso datalake público (...)

#### Solução
Simplesmente alterar para:
> Nós _tratamos_ (...)

Por favor desconsiderem se eu estiver postando no local errado e obrigado pela atenção.

**Comment by fernandascovino** [comment]
Obrigada pelo aviso @vmussa ! Fiz a correção aqui https://github.com/basedosdados/website/commit/dfe41fa0d3ba848e35090066b8295840d9dd758d

Você acha que tem algo mais que podemos fazer para melhorar a página?

**Comment by vmussa** [comment]
Obrigado vocês pelo trabalho incrível, @fernandascovino! Única coisa que notei, fora isso, é que algumas páginas usam o favicon do CKAN em vez de usar o do Base dos Dados. Tentando achar exemplos agora, só vi páginas com o do CKAN, mas tinha a impressão de ter visto algumas com um favicon próprio do basedosdados.

Mais uma vez, obrigado pela atenção!
