### ISSUE TITLE
Nova página: Casos de uso da BD

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/website#104]
Tabela com organizações e usos mapeados: https://docs.google.com/spreadsheets/d/1myjlqEmyv5aEe20PO_lLJxr4uU_XNHYwSM0CoMIxoRg/edit#gid=0

- [x] Mapear projetos que usam a BD
- [ ] Depoimentos e informações sobre organizações que estão usando a BD e como - @rdahis @fernandascovino 
- [ ] Adicionar na home uma seção de Trusted by que redireciona para a página de Casos de uso
- [ ] Criar formulário para informar como você/sua organização usou a BD - colocar check para topar que a gente divulgue o seu trabalho nas nossas redes @nayaramrsc

**Comment by rdahis** [comment]
Fechando pois já temos uma página de estudos de caso e para além disso não está priorizado.
