### ISSUE TITLE
[infra] Decidir destino dos `input_hint`s dos YAML

### ISSUE THREAD

**Issue by vmussa** [basedosdados/website#116]
# Descrição
Em discussão no Discord foi decidido que os `input_hint`s deveriam sair dos campos onde preenche-se os valores nos YAMLs. Atualmente, na branch `develop`, ao menos, os `input_hint`s foram removidos completamentes, restando apenas os comentários gerais como orientação para o usuário preenchedor dos YAMLs.

# Solução
Seria interessante adicionar os `input_hint`s ao fim de cada comentário-descrição, com um ou mais exemplos de como preencher cada campo, como sugeriu o @d116626.

**Comment by d116626** [comment]
Segundo nossas conversas, vamos descontinuar o `input_hint` e dar um improve no `description`.
Aconselho o @rdahis subir o ckan local e ir iterando no `fields_definitions`até os `yamls` ficarem satisfatórios
