### ISSUE TITLE
Clicar em uma tag de um dataset na pagina de busca nao adiciona a tag nos filtros

### ISSUE THREAD

**Issue by polvoazul** [basedosdados/website#12]
![image](https://user-images.githubusercontent.com/1513181/118373306-8bc62680-b58c-11eb-8f04-550cc23d8b35.png)

Clicar em 'saude' deveria adicionar saude aos filtros da busca, mas no momento nao faz nada.

**Comment by fernandascovino** [comment]
tamo chique agora

![image](https://user-images.githubusercontent.com/20743819/151283977-efa9d984-5b54-41ec-870f-746cbbc429e6.png)
