### ISSUE TITLE
Atualizar rodapé

### ISSUE THREAD

**Issue by brenodega28** [basedosdados/website#132]
- [ ] Novas páginas
 - [x] Alterar autores dos ícones
 - [x] Link de serviços
 - [ ] Atualizar link de apoie o projeto para pular para a sessão de atualizar.
 - [x] Mudar link do blog.

Subir na segunda

Visual:
![image](https://user-images.githubusercontent.com/20743819/136613083-c9e7c94a-bb30-43d9-ac07-9660179518a0.png)

**Comment by fernandascovino** [comment]
Dee ser resolvido em #189
