### ISSUE TITLE
Exibir todos os metadados de colunas na página de `bdm_table`.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#149]
Hoje mostra só `name` e `description`. Falta mostrar `bigquery_type`, `temporal_coverage`, etc.

![Screen Shot 2021-10-19 at 9 05 43 PM](https://user-images.githubusercontent.com/6617207/138006701-1c6fa659-bcf2-46f8-b8b0-feb21e3af233.png)

- [x] Fazer o design
- [x] Implementar no site

**Comment by fernandascovino** [comment]
@rdahis esta em standby ate organizar s metadados ne? vou deixar como prioridade baixa enquanto isso

**Comment by rdahis** [comment]
Esse já tá liberado pra andar no frontend. No backend estou adicionando um campo novo (`observations`), mas não vai mudar os campos que já temos.
