### ISSUE TITLE
Novos endpoints para a Home

### ISSUE THREAD

**Issue by brenodega28** [basedosdados/website#15]
1. Endpoint de listagem das n bases mais populares (n passado como parâmetro na url ?page_size=n).
2. Endpoint de listagem das n bases mais recentes (n passado como parâmetro na url ?page_size=n).
3. Endpoint de inscrição de um email na newsletter.

Informações necessárias da base de dados para os pontos 1 e 2:

- Categorias
- Título
- Tags (acho que é categoria novamente, confirmar no figma)
- Tamanho (se existir)
- Quantidade de tabelas (se existir)
- Quantidade de links externos (se existir)
- Último usuário que atualizou a base
- Data de última atualização da base
- Link para a base de dados (provavelmente é um slug)

**Comment by vncsna** [comment]
> Link para a base de dados (provavelmente é um slug)

@brenodega28 o que é um slug neste caso?

**Comment by brenodega28** [comment]
Slug é tipo um id da base só que com mais cara de nome e sem espaço, acento, etc

**Comment by vncsna** [comment]
Queria uma segunda opinião, podemos usar este [endpoint](https://developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences) (subscribe) no caso de se inscrever na newsletter? A descrição do endpoint inclui uma frase que achei que poderia proibir o nosso caso.

`/communication-preferences/v3/subscribe`

> This API is not valid to use for subscribing a contact at a brand or portal level and will return an error.

**Comment by vncsna** [comment]
Apenas o endpoint da newsletter não funcionou..
