### ISSUE TITLE
Adicionar informação de atualização dos dados

### ISSUE THREAD

**Issue by d116626** [basedosdados/website#150]
## Contexto

Hoje existe mais de um metadado referente a atualização dos dados, precisamos exibir eles no FE e deixar claro ao que se refere cada um deles.

![image](https://user-images.githubusercontent.com/8954716/138142052-f08945a9-5d1c-4975-a5e1-81d1602e0c95.png)

**Comment by rdahis** [comment]
Acho que decidimos continuar usando cobertura temporal como o campo relevante para as datas que temos na BD.
