### ISSUE TITLE
[site] Demandas Dahis

### ISSUE THREAD

**Issue by brenodega28** [basedosdados/website#151]
- [ ] Exibir (no formulário, na página de conjunto, na busca, na home) cobertura temporal a partir do formato de intervalos `T(d)T`. Esse `T` pode ser `YYYY`, `YYYY-MM`, `YYYY-MM-DD`. Exemplo: `1998(1)2020`. (Falta ver com o backend)
- [ ] Campo `covered_by_dictionary` em `bdm_table` ser exibido automaticamente como sim se qualquer coluna da tabela for coberta por dicionário. (Deletar campo de `bdm_table`?) (Fácil)
- [ ] Quebrar valores conjuntos nos metadados. (Médio)
- [x] Após clicar em submit na edição, ele cai para o footer. Deveria jogar pra visão em cima.
- [x] Criar botão de "excluir conjunto" na página de conjunto. (para podermos excluir o [Finbra](https://basedosdados.org/dataset/br-tesouro-finbra))
- [x] Na página de conjunto, exibir "Metadados do conjunto" acima de "Recursos".
- [x] Poder desmarcar opções após seleção em campos múltipla escolha (e.g. cobertura espacial). (No Mac usar o command e apertar no input)
- [ ] Ter `available_options` traduzido durante a edição de formulários. (Complicado)
- [ ] Dá erro quando clico nos metadados desse [conjunto](https://staging.basedosdados.org/dataset/9fdeaf3e-1fbe-4b40-9c69-a1f219ada0c0). (Médio)
- [ ] Em campos de string longa (descrições, notas), não tá podendo dar Enter e escrever coisas em múltiplas linhas. Idealmente seria no formato Markdown, com bullets, etc. (Complicado)
- [ ] Fazer com que a descrição de conjuntos e recursos apareçam com linhas vazias entre parágrafos. Hoje ele não dá essa possibilidade. (Fácil)
- [x] Colocar para buscar datasets pelo name e não id.
- [x] Exibir "link externo" e "tabela tabela" quando tive só 1.
- [x] Consertar botão novo conjunto.
- [x] Revisar quais campos aparecem no formulário de edição de cada objeto.
- [x] Quando um conjunto só tem um ano de cobertura temporal, deveria aparecer só o ano sem intervalo. Exemplo aqui deveria aparecer só "2010", e não "2010 - 2010".

**Comment by Math-Avila** [comment]
@brenodega28 mesma coisa do "demandas Nay", quer que eu quebre isso em diferentes issues?

**Comment by fernandascovino** [comment]
@rdahis quebrar em novos issues e fechar esse aqui

**Comment by rdahis** [comment]
Fechando porque as tarefas abertas estão sendo passadas para o projeto https://github.com/orgs/basedosdados/projects/12.
