### ISSUE TITLE
Nova funcionalidade de conjunto: Pedidos LAI

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#152]
Ver referência da página "Achados e Pedidos" (Transparência Brasil)

Depende de #157 

- [x] Colocar link da planilha @rdahis 
- [x] Criar páginas no Figma.
- [x] Revisar pagina no Figma
- [x] Criar botões de "novo pedido LAI"
- [x] Implementar páginas no site.

**Comment by brenodega28** [comment]
@d116626
<img width="565" alt="Captura de Tela 2021-11-29 às 15 32 53" src="https://user-images.githubusercontent.com/26328476/143923478-8759c9f2-df67-4c09-8620-78eb645933e2.png">
 
Ele não está aceitando o tipo information_request.

**Comment by rdahis** [comment]
@fernandascovino e @nayaramrsc como anda a parte de FE aqui? O BE tá pronto para receber entradas.

Por enquanto podemos hardcode o logo do Fiquem Sabendo como organização parceira. Já criei um campo pra isso mas falta umas coisas de BE para funcionar.
