### ISSUE TITLE
1-click-download parece não estar funcionando

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#16]
Várias tabelas estão com "download indisponível".

<img width="1196" alt="Screen Shot 2021-06-09 at 6 47 12 PM" src="https://user-images.githubusercontent.com/6617207/121434097-2ed34b80-c953-11eb-8385-800fc7158660.png">

**Comment by rdahis** [comment]
@polvoazul consegue ver isso em algum momento? Tá quebrado pra todas as tabelas.

**Comment by d116626** [comment]
Parece que foi resolvido na migração: https://staging.basedosdados.org/dataset/br-geobr-mapas/resource/70e9af24-9ddd-4166-9564-8a30d48ab2d1

**Comment by rdahis** [comment]
Mas não de todos né. Exemplo: https://staging.basedosdados.org/dataset/br-bd-diretorios-brasil/resource/9046b938-b361-4c3c-a5e7-a549dfc48f2b

Sabe o que explica funcionar em uns mas não em outros?
