### ISSUE TITLE
Filtros na busca: cobertura espacial, cobertura temporal, entidade, unidade temporal, frequência de atualização

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#160]
Endpoints já disponíveis:
* `bd_dataset_search`
- [x] Cobertura Espacial
- [x] Cobertura Temporal
- [x] Entidade
- [x] Frequência de Atualização (necessita backend)

**Comment by brenodega28** [comment]
@d116626 @rdahis Filtro de frequência de atualização não está feito no backend.

**Comment by brenodega28** [comment]
<img width="167" alt="Captura de Tela 2021-11-23 às 19 06 44" src="https://user-images.githubusercontent.com/26328476/143136775-60e840d3-6b74-46af-9c37-460982eb9749.png">

**Comment by d116626** [comment]
> @d116626 @rdahis Filtro de frequência de atualização e Cobertura espacial não estão feitos no backend.

resolvido!

https://staging.basedosdados.org/api/3/action/bd_dataset_search?spatial_coverage=north_america
https://staging.basedosdados.org/api/3/action/bd_dataset_search?update_frequency=thre_years
