### ISSUE TITLE
[site] Erros Formulário

### ISSUE THREAD

**Issue by brenodega28** [basedosdados/website#161]
- [ ] Colunas
- [ ] Partições (não é obrigatório)
- [ ] Raw files
- [ ] Site
- [ ] Auxiliary files

**Comment by d116626** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/8954716/139776069-135f9ac1-ee16-4532-b25e-8775a6de1db8.png">
@brenodega28  acho que só remover não tá rolando

**Comment by rdahis** [comment]
Outro erro: ao editar metadados de conjunto, preencher a coluna "url Github" dá erro na hora de publicar. Pede para contactar a equipe de tecnologia.

**Comment by rdahis** [comment]
Ao criar uma `bdm_table` nova pelo site, deu esse erro:
![Screen Shot 2021-11-02 at 11 45 13 AM](https://user-images.githubusercontent.com/6617207/139870264-9ed6bc24-feec-4098-a8b2-9f0aced2ea7a.png)

**Comment by rdahis** [comment]
Ao criar um `dataset` pelo site, dá erro pedindo `.type is a required property`.

**Comment by brenodega28** [comment]
> <img alt="image" width="791" src="https://user-images.githubusercontent.com/8954716/139776069-135f9ac1-ee16-4532-b25e-8775a6de1db8.png">
> 
> @brenodega28 acho que só remover não tá rolando, ta dando o mesmo erro quando vai editar metadado de tabela
<img width="250" alt="Captura_de_Tela_2021-11-09_as_19 58 13" src="https://user-images.githubusercontent.com/26328476/141019378-88655708-02d0-4f18-8fdd-45ed0bd2421d.png">

Esta vindo errado da API, precisar ter um description.
