### ISSUE TITLE
Criar campo de descrição curta

### ISSUE THREAD

**Issue by brenodega28** [basedosdados/website#165]
Ideia é ter até 160 (320?) caracteres para aparecer na página de conjunto.

**Comment by Math-Avila** [comment]
@brenodega28 é na visão em lista que você se refere? Nayara e @fernandascovino isso precisa ser priorizado eu diria que não, mas de qualquer forma precisaria de um mock up pra gente ter mais clareza de como ficaria antes de começar a desenvolver.

**Comment by fernandascovino** [comment]
@rdahis @brenodega28 não precisaremos mais do "Leia mais: " com esse novo campo?

**Comment by rdahis** [comment]
Verdade, não vai precisar.

**Comment by rdahis** [comment]
Closed by #211.
