### ISSUE TITLE
[site] Demandas Nayara

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#168]
- [x] Deixar o cinza do menu da tabela do tamanho do botão e mudar a cor de acordo com o figma
- [x] Trocar ícones de temas (contornos mais fortes/visíveis) - pronto no Figma
- [x] Falta o + no ícone de tabelas tratadas na Home - pronto no Figma
- [x] Trocar logos na seção de parcerias na Home (tamanhos mais próximos) - pronto no Figma
- [x] Forma do botão "Entre em contato" na seção de parcerias da Home está diferente dos demais
- [x] Letra minúscula no "inicial", tirar o "4." dos passos do PIX, tirar o ">>" e o sublinhado do "Entre em contato conosco" na seção de apoie da Home
- [x] Aumentar o tamanho do destaque azul do pedido de doação no download dos dados igual o outro
- [x] Faz sentido "Tabelas tratadas BD+" e "Links externos" serem clicáveis na página de conjunto sendo que não direciona para nada? Talvez cor de destaque ao navegar entre as tabelas e entre os links?
- [x] Sombra do buscador da página de Dados está diferente das demais
- [x] Faz sentido só BD+ ser clicável em "x tabelas tratadas BD+" nos cards e na página de Dados e direcionar para filtro de forma de consulta?

**Comment by Math-Avila** [comment]
@brenodega28 quando tem várias demandas no mesmo card assim você faz tudo de uma vez ou criar vários issues pra ir completando? Separar e colocar uma label correta me parece a melhor opção.
