### ISSUE TITLE
[site] Trocar cor roxa das caixas de código para maior contraste

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#169]
É difícil ler o texto com as cores atuais. Melhor ser um tom tipo solarized light.

![Screen Shot 2021-11-07 at 12 22 02 PM](https://user-images.githubusercontent.com/6617207/140651237-4d60af8e-5ceb-4428-95e2-479953b17c42.png)

Mudar:
- [ ] SQL
- [ ] Python
- [ ] R

**Comment by nayaramrsc** [comment]
![image](https://user-images.githubusercontent.com/88157499/140792408-d1261e85-32e2-4dbe-9672-972a92409c8b.png)

alguns testes aqui

**Comment by fernandascovino** [comment]
@rdahis nao acho dificil de ler o texto, o contraste na real parece muito bom, com exceção talvez do roxo... @polvoazul o que ce acha?

@nayaramrsc o contraste das cores está muito baixo, não da para ler com esses fundos

**Comment by rdahis** [comment]
Concordo que o problema na verdade é esse roxo aí :-)

**Comment by nayaramrsc** [comment]
os [carbons](https://carbon.now.sh/) tem padrões de cores por linguagem, se acharem uma boa

SQL, por exemplo:
![image](https://user-images.githubusercontent.com/88157499/140993443-9d4ac3d0-aea6-41ff-b18e-def588ea31e2.png)

Teste de visão de cores:
![image](https://user-images.githubusercontent.com/88157499/140994026-5a8c8002-2d6f-47ae-9458-68226f42562b.png)

**Comment by brenodega28** [comment]
> os [carbons](https://carbon.now.sh/) tem padrões de cores por linguagem, se acharem uma boa
> 
> SQL, por exemplo: ![image](https://user-images.githubusercontent.com/88157499/140993443-9d4ac3d0-aea6-41ff-b18e-def588ea31e2.png)
> 
> Teste de visão de cores: ![image](https://user-images.githubusercontent.com/88157499/140994026-5a8c8002-2d6f-47ae-9458-68226f42562b.png)

Vai ser esse aqui.

**Comment by nayaramrsc** [comment]
![image](https://user-images.githubusercontent.com/88157499/143142248-fb62795b-d261-44e4-ac86-23a9ef985413.png)

@brenodega28 
#ACE158
#E44748
#FFDF54
