### ISSUE TITLE
Fazer filtros ordenarem elementos melhor

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#182]
## Contexto

Hoje está aparecendo aleatoriamente e está confuso. Exemplo:

![Screen Shot 2021-11-29 at 3 43 39 PM](https://user-images.githubusercontent.com/6617207/143925497-4589bbbb-c92c-4ece-b56c-8fc365edf8e1.png)

Opções:
- Ordenar exatamente como está no pydantic.
- Ordenar por número de elementos em cada enum.

**Comment by d116626** [comment]
Provavelmente tem mexer nessa parte do código 

https://github.com/basedosdados/website/blob/3223b9ad4a81723af865a0859bbb351270103705/ckanext-basedosdados/ckanext/basedosdados/actions/get.py#L311-L326
