### ISSUE TITLE
Copiar o banco de prod para dev com frequência regular

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#184]
**Motivação**

A equipe de dados vai trabalhar com metadados em staging, com a aprovação e publicação em prod sendo feita via `table approve`. Mas pra isso os metadados em staging tem que estar atualizados.

**Solução**

Copiar o banco de prod para dev com frequência regular. Idealmente todo dia.

**Comment by rdahis** [comment]
Foi feito né @guialvesp1?

**Comment by guialvesp1** [comment]
> Foi feito né @guialvesp1?

Sim, a recorrência desta atualização é semanal, sendo realizada todo domingo.
