### ISSUE TITLE
Busca na página principal às vezes não funciona

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/website#191]
### Contexto
Algumas pessoas já relataram esse problema: quando é feita a busca na barra o termo é perdido depois, e aparecem todos os itens do catálogo ao invés do filtro pelo termo buscado.

### Relatos

**Relato 1:**
Eu mesma tentei buscar "covid19" e não funciona de primeira, mas se retorno a página principal e busco novamente funciona.

**Relato 2:**
"Pessoal, quando abro o site e clico para pesquisa uma palavra chave e dou Enter, é aberto a página de busca, mas não com a minha palavra de busca. Acho que o objetivo seria já realizar a busca, certo?

dá pra ver que a URL tenta buscar a palavra chave, nas volta para https://basedosdados.org/dataset?order_by=score"

![image](https://user-images.githubusercontent.com/20743819/147699040-7586be8e-62c0-42d4-a267-bf3672ff063d.png)

**Comment by mfagundes** [comment]
Não sei se isso é relevante, mas no header da requisição da busca ele passa o referer como "https://basedosdados.org/dataset?order_by=score", que é o endereço que a @fernandascovino reportou como o retorno.

Um detalhe é que esse bug nunca aconteceu comigo, mas só testei no Chrome (Mac e PC)
