### ISSUE TITLE
Transformar `temporal_coverage` em lista de intervalos.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#201]
- [ ] tabela
- [ ] coluna
- [ ] dicionário
- [ ] pedido LAI

**Comment by rdahis** [comment]
Atual:

[2001, 2002, 2003, 2004, 2008, 2009]

Desejado:

[2001(1)2004, 2008(1)2009]

**Comment by fernandascovino** [comment]
@rdahis isso é na API ou no FE? Se for FE, o mais intuitivo parece ficar listado não?

**Comment by rdahis** [comment]
Isso é tudo, BE e FE haha. Já tô lidando com todas as modificações necessárias em #212.

**Comment by rdahis** [comment]
Closed by #211.
