### ISSUE TITLE
[infra] Criar campos `uncompressed_file_size` e `compressed_file_size` de `bdm_table`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#222]
## Contexto

@polvoazul começou esse trabalho lá atrás [aqui](https://github.com/basedosdados/infra).

Novos campos de metadados de `bdm_table` no pydantic:
* `uncompressed_file_size` (em bytes)
* `compressed_file_size` (em bytes)

**Resultado esperado**: https://staging.basedosdados.org/api/3/action/package_show?name_or_id=br-senado-cpipandemia

## Tarefas

- [x] Criar funções para calcular tamanhos comprimido e não comprimido do arquivo
- [ ] Fazer migração

**Comment by fernandascovino** [comment]
Não entendi, fazer funcionar não é na API? É outro repo não?

Se for especificamente mostrar esses metadados corretos, aí é frontend
