### ISSUE TITLE
Criar classificação de fontes de dados

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#228]
### Campos

* Metadados disponíveis hoje de links externos:
    * has_structured_data
    * has_api
    * is_free
    * requires_registration
    * availability
    * country_ip_address_required
    * license
    * update_frequency
* Metadados que podemos criar:
    * Limpeza requer compatibilização (entre anos, etc)
    * Se precisa de dicionário, tem dicionário de fácil acesso, completo, atualizado
    * Se precisa de documentação, tem arquivos auxiliares (descrições, notas técnicas, etc)

### Classificação de campos

* Importância de cada campo (0-10)
    * has_structured_data: 10
    * has_api: 4
    * is_free: 8
    * requires_registration: 4
    * availability: 8
    * country_ip_address_required: 5
    * license: 10
    * update_frequency: 5

* Positivos
    * has_api = yes
    * requires_registration = no
    * country_ip_address_required = None
    * update_frequency not in [uncertain, unique]
    * has_structured_data = yes
    * is_free = yes
    * availability = 'online'
    * license = something public

### Nota final

nota = 1/(\sum_{campo} peso do campo) * \sum_{campo} (peso do campo * indicador do campo)

### Filtros na busca

* Bom: nota >= 8
* Médio: nota in [6, 8]
* Ruim: nota <= 6

**Comment by fernandascovino** [comment]
@rdahis acho maneira a pontuacao, mas ainda reitero que não acho útil o filtro por qualidade do dado original

gosto bastante de trocar `link externo` para `dados originais`!! tem que mudar em:
- recurso do conjunto
- documentacao
- filtro
- card do conjunto na busca *

\* aqui só me parece estranho ter `2 dados originais` - poderia ser `tabelas`, `recursos`, `fontes`...?:

![image](https://user-images.githubusercontent.com/20743819/152054284-1a719353-2bb7-42c6-9b41-a259e2fa9d11.png)

**Comment by fernandascovino** [comment]
@rdahis alterei o titulo aqui para focar numa tarefa só, se achar que tem outro assunto que não inclui classificacao abre outro issue por favor ;)
