### ISSUE TITLE
Fazer a action `bd_available_options_dict` lidar com chaves definidas em múltiplas `available_options`.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#233]
### Contexto

Hoje a ação `bd_available_options_dict` devolve um dict único com todas `available_options`, pegando o label associado. Mas se tiverem opções definidas em mais de um `available_options`, ele pega o label de um deles só.

Exemplo: as opções `person`, `household`, `year` estão definidas dentro de `entity.py` e `measurement_unit.py` com labels diferentes. Aí no filtro de `observation_level` aparece erradamente `pessoa`, `domicílio`, `ano`.

### Solução

Ter alguma forma de separar opções por tipo de categoria e o front-end entender isso de acordo com o campo.

**Comment by fernandascovino** [comment]
@rdahis o que tem de frontend aqui? ta em grego hahah

**Comment by rdahis** [comment]
> @rdahis o que tem de frontend aqui? ta em grego hahah

Acho que pode tirar FE mesmo =D
