### ISSUE TITLE
Carrossel de temas

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#274]
- [x] Adicionar possibilidade de tirar a seleção do tema
- [x] Adicionar possibilidade de selecionar mais de um tema
- [x] Fixar espaçamento entre os temas
- [x] Ajustar o final do carrossel
- [x] Corrigir o alinhamento do ícone do tema quando é selecionado (levemente diferente do não selecionado)
- [x] Tirar setas na versão mobile?

**Comment by rdahis** [comment]
@nayaramrsc @AldemirLucas não esqueçam de marcar quais issues serão fechadas por quais PRs na hora de dar merge. Porque aí já fecha automaticamente e vamos limpando nosso backlog :-)
