### ISSUE TITLE
Adicionar ordenamento de conjuntos por relevância

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#276]
**Problema**
Aprimorar ordem do resultado da busca por conjuntos de dados

**Hipóteses**
Apresentar resultados de acordo com a ordem de temas dos conjuntos. 
Mas observamos que a ordem dos temas de um conjunto é alfabética, teria que reorganizar.
ex.:
![Image](https://user-images.githubusercontent.com/88157499/226976217-e74aa7b9-a078-41f2-8a8f-116a9af4027d.png)

**Comment by laura-l-amaral** [comment]
Já foi executado, agora estamos trabalhando em novos aprimoramentos basedosdados/backend#573
