### ISSUE TITLE
[migração] Migrar dados de YAML para novo formato e subir para banco

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/website#30]
- comparar YAML atual com aos objetos atuais [dataset, table], criar um documento com esse mapa @rdahis
- baixar o package atual, e dar merge com o yaml
- fazer modificações necessárias para ficar igual aos objetos atuais criando um [package](http://0.0.0.0:5000/api/3/action/package_show?id=br_abrinq_oca) 
- checar se tudo passa pelo validate

[Validadores/Objetos](https://github.com/basedosdados/website/tree/api-validators/ckanext-basedosdados/ckanext/basedosdados/validator)

**Comment by vncsna** [comment]
Continua em https://github.com/basedosdados/website/issues/64
