### ISSUE TITLE
Traduzir `measurement_unit` como álgebra

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#325]
No front-end, traduzir unidades de medida complexas a partir da string (metadado) e das traduções de available options. O output seria em notação de LaTeX para dar conta de super-escritos, parêntesis, etc.

**Exemplos de tradução**:

* `'meter/second'` para `metro/segundo`
* `'meter^2'` para `metro^2` (formato latex com 2 super-escrito)

**Comment by rdahis** [comment]
> Aplicando a tradução, e no render do componente fazendo a transcrição para o LaTex.
> 
> ![Image](https://user-images.githubusercontent.com/82185307/196263920-e18c9921-ef32-4570-aebf-4188af67c277.png)

Maneiro!!!

**Comment by crislanealves** [comment]
Fechando, contemplado no PR https://github.com/basedosdados/website/pull/497
