### ISSUE TITLE
[infra] criar testes para forms 

### ISSUE THREAD

**Issue by d116626** [basedosdados/website#33]
Criar algum teste que faça o check do forms, inicialmente pode ser um teste que cheque se os imports necessaios para rodar os forms estão funcionando. Os testes ficam em `/ckanext-basedosdados/ckanext/basedosdados/tests`

**Comment by vncsna** [comment]
Eu creio que erros com imports sejam bem raros, ainda mais após a estabilidade de novo site com novos forms. Talvez até criar testes após os novos forms (não sei muito se vai mudar a programação desta parte).

**Comment by rdahis** [comment]
Fechando por enquanto porque parece estar resolvido com os formulários do site e templates de yamls.
