### ISSUE TITLE
CKAN, liberar acesso pela URL

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#342]
- [ ] Liberar acesso ao ckan atraves da url exemplo: `https://basedosdados.org/dataset/edit/br-inmet-bdmep` e `https://basedosdados.org/dataset/groups/br-inmet-bdmep`

O acesso ao CKAN fica limitado ao login da conta, url de edição são bloqueadas com erro 404, no ambiente localhost:5000 podemos ter acesso a  edição pelo CKAN.
![image](https://user-images.githubusercontent.com/82185307/169608618-6094957c-6cc5-4994-824a-d62685a75fe3.png)

objetivo de conseguir em PROD e staging ->
![image](https://user-images.githubusercontent.com/82185307/169608180-5a906ac1-c8ca-4d1e-8f62-1c51b1fb7562.png)

**Comment by rdahis** [comment]
A utilidade desse acesso será principalmente poder editar as etiquetas e temas de conjuntos. Hoje ainda não temos a infra suportando isso.

**Comment by rdahis** [comment]
Isso aqui seria muito custoso fazer? Se fosse rápido seria útil, antes da migração ficar pronta.

**Comment by guialvesp1** [comment]
> Isso aqui seria muito custoso fazer? Se fosse rápido seria útil, antes da migração ficar pronta.

@AldemirLucas Após a liberação no NGINX, o por que não foi possível o acesso a este endpoint?

**Comment by guialvesp1** [comment]
> Isso aqui seria muito custoso fazer? Se fosse rápido seria útil, antes da migração ficar pronta.

@rdahis consiste na criação de um novo endpoint, para chegar até a edição de um package. Devido a rota /dataset estar mapeada para o container do nextjs. Então devido a falta de conhecimento da equipe e falta de documentação para criação de endpoints (tipo put) torna a tarefa custosa.
