### ISSUE TITLE
Botão de deletar conjunto não responde

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#343]
Ao tentar clicar no botão de deletar um conjunto, nada acontece.

Gostaria de deletar esse conjunto em produção: https://basedosdados.org/dataset/sistema-de-avaliacao-da-educacao-basica

![Screen Shot 2022-05-23 at 15 45 37](https://user-images.githubusercontent.com/6617207/169886215-bf57fa68-44b9-4b48-ab40-c0e50cc6a787.png)

**Comment by AldemirLucas** [comment]
Localmente( `localhost` ) o mesmo conjunto eu conseguir deletar pelo botão de remover

**Comment by AldemirLucas** [comment]
@rdahis esse bug ainda persiste?

**Comment by rdahis** [comment]
> @rdahis esse bug ainda persiste?

Acabei de testar aqui, e sim =/
