### ISSUE TITLE
Feature/ Tradução da BD

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#351]
`i18n` componente de tradução;

Processo:
- implementar a biblioteca do i18n (https://www.i18next.com/).
- todo o conteúdo que o usuário ver tem que ser transferido para o arquivo de tradução i18n.
- colocar referências do html para o  arquivo de tradução.

Tempo decorrido:
- i18n implementação de 1 dias
- avaliar a quantidade de texto para ser traduzido
- 8h para traduzir 1000 linhas em média

**Comment by fernandascovino** [comment]
parece bom por mim, esse tempo de implementação de 1 dia é para subir e testar o componente em `staging`?
