### ISSUE TITLE
Renomear `br_bd_diretorios_brasil` para `br_bd_diretorios_br`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#376]
- [x] Migrar a classe Enum de país em `available_options/spatial_coverage` para vir da `spatial_coverage_tree`.
- [ ] Migrar em todos os lugares.
    * BigQuery
    * Todos os `directory_column`.
    * Documentação
    * READMEs
    * MetaBases
- [ ] Migrar colunas no diretório de país para `nome_pt`, `nome_en`, etc. Atualizar script de criação de `spatial_coverage_tree`.
       - [ ] Referencia: https://github.com/basedosdados/website/blob/master/ckanext-basedosdados/ckanext/basedosdados/validator/available_options/spatial_coverage/update_tree_from_bd

```python
    SELECT
    LOWER(CONCAT('sa.br.', sigla_uf, '.', id_municipio)) AS id,
    nome AS `label__pt`, # mudar para  nome__pt
    nome AS `label__en`, # mudar para  nome__pt
    FROM `basedosdados.br_bd_diretorios_brasil.municipio`
```

**Comment by laura-l-amaral** [comment]
@rdahis  isso ainda é algo? Posso fechar como não priorizado?

**Comment by rdahis** [comment]
Podemos fechar como não planejado por enquanto sim. Se vier a fazer isso, será parte de um esforço maior de internacionalização de conjuntos, que envolveria múltiplos projectos no GCP, VIEWs, etc, etc.
