### ISSUE TITLE
Criar tabela sobre a equipe

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#413]
- [x] Criar duas tabelas no BigQuery: `pessoa`, `equipe`
- [x] Criar código que roda query e atualiza o csv local. Copiar do `spatial_coverage_tree`.
- [x] Criar endpoint chamado `team` retornando informações para consumo do front-end.

**Comment by rdahis** [comment]
@crislanealves algumas tarefinhas que pensei:

* Tirar coluna `nome_pessoa` da tabela `equipes`.
* Incluir colunas `data_entrada` e `data_saida` na tabela `pessoas` para marcar as datas das pessoas nas equipes.
* Incluir linhas em ambas as tabelas para pessoas que já saíram: Matheus, Hevilyn, Breno, Caio, Isadora, Kaline, etc!
