### ISSUE TITLE
Criar metadado de atualização automática dos dados

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#414]
Ideia: 

Criar um metadado de quando o dado esta sendo atualizado automaticamente, pra aparecer em algum lugar no frontend pro usuário.

Possibilidade:
Nome do campo: `is_updated_automatically`.
Tipo: Enum `yes_no`

**Comment by rdahis** [comment]
Pegar o metadado de `update_frequency` + `last_updated` para exibir frequência de atualização. Podendo representar manual ou automático.

**Comment by rdahis** [comment]
Implicaria uma tarefa para a equipe de dados de dar uma limpada no campo `update_frequency`. Deixar preenchido só para tabelas que de fato tenhamos um compromisso de atualização regular. @laura-l-amaral

**Comment by vncsna** [comment]
@rdahis podemos fechar essa issue?

**Comment by rdahis** [comment]
Pode.
