### ISSUE TITLE
Ordenar tabela por equipes e cargos.

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/website#431]
É preciso ordenar para que apareça na ordem certa na página de 'Quem Somos'.

	- Fundadores:
		- Ricardo (Presidente)
		- Fernanda (Diretoria)
		- Ordem Alfabética 
	
	- Associado: 
	        - Ordem Alfabética	 
		
	- Administrativo:
		- Ordem Alfabética
	
	- CPP:
		- Coordenador
		- Ordem Alfabética
		
	- Comunicação:
		- Coordenador
		- Ordem Alfabética
				
	- Dados:	
		- Coordenador
		- Ordem Alfabética
		
	- Infra:
		- Coordenador
		- Ordem Alfabética
			
	- Website:
		- Coordenador
		- Ordem Alfabética
		
	- Conselho:
		- Ordem Alfabética

**Comment by rdahis** [comment]
Feito via front-end.
