### ISSUE TITLE
[infra] Verificar não atualização de campos de metadados feitas pelas pipelines

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/website#466]

**Comment by guialvesp1** [comment]
Foi notado que o CKAN não está concluindo o re-index, tendo como retorno o erro: `ERROR [ckan.lib.search] Error while indexing dataset 1f6952e2-5def-4fa0-9f95-196d75c7c5b6: ValueError("invalid literal for int() with base 10: ''")`, o dataset em questão é o https://basedosdados.org/dataset/acessos-dos-servicos-de-tv-por-assinatura-no-brasil?external_link=Baixar

**Comment by mfagundes** [comment]
Rodei a pipeline de contabilidade na mão no dia 30/11/2022. A data foi atualizada, mas incorretamente. Verificar se a data do cluster está errada. Atualizou para 2022-11-29 00:09:21
