### ISSUE TITLE
BD Analytics - Endpoint

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#483]
Endpoint:  `/api/3/action/bd_analytics`

Ajuste na data de inicio da capitação dos dados, o mais próximo possível da criação do site.

https://perguntas.basedosdados.org/dashboard/98-acessos-bd
![image](https://user-images.githubusercontent.com/82185307/194637706-8fecf5ff-eebe-49d2-b1de-875e79f3ab87.png)

**Comment by lucascr91** [comment]
Precisava apenas fazer uma alteração. Commitei direto.
