### ISSUE TITLE
Otimização do Site

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#498]
Branchs e Pull request referentes a essa issue: 
 - https://github.com/basedosdados/website/commit/ddbba16ad3ab86da2daa4a7fc61a4c9829096605
 - https://github.com/basedosdados/website/commit/b6112296933052228dbe3314674f2786f3d13379
 - https://github.com/basedosdados/website/commit/d5fe7408bbef62f7612ec7063893de0de4de3095
 - https://github.com/basedosdados/website/commit/ef272bed6bed96ac7575fbb7d34206ef105b8a33
 - https://github.com/basedosdados/website/commit/cf47d632d46608d5c280e484d3e1715dcda7dd16
 - https://github.com/basedosdados/website/pull/533/commits/7e49ea92bacdf609d2c8f37d0234e950549a2f6b
____
Doc com detalhes de avaliação: https://docs.google.com/document/d/10sxxVWnlAQm9tx5pK9I0M84k54Q2Dh3P2k2heaU_Gpo/edit

Objetivo de conseguir aumento considerável em todas as categorias(performance, accessibility, best practices ,SEO):

| Pagina | Performance | Accessibility | Best practice | SEO |
| -- | -- | -- | -- | --|
| Home | 90 | 95 | | 91 |
| Dados | | 94 | | 100 |
| Dataset | 95 | 95 | | |
| Perguntas frequentes | | 93 | | 90 |
| Serviços | | | | |
| Estudos de caso | | 93 | | 91 |
| Quem somos | 99 | 93 | | 91 |
| Transparência | | | | |
| Contato | 99 | 92 | | 90 |

**Comment by laura-l-amaral** [comment]
já alteramos todo o site, essa issue não faz mais sentido
