### ISSUE TITLE
BD Analytics - Endpoint - Website_users

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#499]
Adicionar métrica `activeUsers` no campo de `website-users`

![image](https://user-images.githubusercontent.com/82185307/197042742-188925a6-948d-433e-855d-6825bce7a3d4.png)

**Comment by lucascr91** [comment]
eu fiz a migração da base para adicionar a nova coluna, mas quando fui editar a pipeline, notei que o campo activeUser não está disponível na API, apenas na UI. A referência dos campos disponíveis na API estão aqui [UA Dimensions & Metrics Explorer](https://ga-dev-tools.web.app/dimensions-metrics-explorer/)

Quando tentei puxar o activeUsers no python, deu esse erro:

```python
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json returned "Unknown metric(s): ga:activeUsers
For details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.". Details: "Unknown metric(s): ga:activeUsers
```

Eu e  Lessa achamos melhor mudarmos a definição do dado no frontend. Em vez de usar _usuários na plataforma_ para vamos passar a usar _usuários no ultimo mês_. Esta última informação está disponível na API e já está na tabela de prod no BQ.
