### ISSUE TITLE
Ordenar exibição de recursos na página de conjunto

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#522]
**Problema**
Hoje os recursos (tabelas, pedidos LAI, fontes externas) tem ordem de exibição fixa. Mas muitas vezes, conforme vamos excluindo e publicando dados, a ordem fica esquisita. 

**Objetivo**
Seria útil poder jogar para cima ou para baixo.

**Hipóteses**
–

**Informações adicionais**
Questões:
* Precisamos de metadado específico de `position`? (No CKAN original é assim)
* Tem como ser uma coisa simples "point and click" via front-end?

**Valor da demanda**
Escolha uma das opções abaixo:
- [ ]  A solução não tem nenhuma relação com nossos OKRs
- [ ]  A solução tem relação indireta com nossos OKRs
- [x]  A solução tem relação direta com nossos OKRs

Escolha uma das opções abaixo:
- [ ]  A solução aumenta pouco a satisfação de usabilidade da plataforma
- [x]  A solução aumenta consideravelmente a satisfação de usabilidade da plataforma
- [ ]  A solução aumenta muito a satisfação de usabilidade da plataforma

Escolha uma das opções abaixo:
- [ ]  A solução é para a equipe
- [ ]  A solução é para a organização
- [x]  A solução é para o usuário

**Esforço da demanda**
Escolha uma das opções abaixo:
- [x]  A solução requer alteração pontual no design
- [ ]  A solução requer adaptação de algo existente no design
- [ ]  A solução requer desenho do zero

Escolha uma das opções abaixo:
- [ ]  A solução requer alteração pontual no desenvolvimento
- [ ]  A solução requer adaptação de algo existente no desenvolvimento
- [x]  A solução requer desenvolvimento do zero

Escolha uma das opções abaixo:
- [ ]  A solução envolve apenas o time plataforma
- [ ]  A solução envolve outros times de modo pontual, além do time plataforma
- [x]  A solução envolve outros times de modo mais que pontual, além do time plataforma

**Comment by laura-l-amaral** [comment]
Ajustado
