### ISSUE TITLE
Incluir opção de download dos arquivos auxiliares

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#528]
**Problema**
Eu fico frustrada quando não encontro arquivos que me auxiliam a entender e utilizar os dados

**Objetivo**
Fazer download de arquivos auxiliares

**Hipóteses**
- Acesso através de um botão 
- Acesso através de um link com ícone de download em seção específica nas informações adicionais da tabela

**Informações adicionais**
–

**Valor da demanda**
Escolha uma das opções abaixo:
- [ ]  A solução não tem nenhuma relação com nossos OKRs
- [ ]  A solução tem relação indireta com nossos OKRs
- [x]  A solução tem relação direta com nossos OKRs

Escolha uma das opções abaixo:
- [ ]  A solução aumenta pouco a satisfação de usabilidade da plataforma
- [x]  A solução aumenta consideravelmente a satisfação de usabilidade da plataforma
- [ ]  A solução aumenta muito a satisfação de usabilidade da plataforma

Escolha uma das opções abaixo:
- [ ]  A solução é para a equipe
- [ ]  A solução é para a organização
- [x]  A solução é para o usuário

**Esforço da demanda**
Escolha uma das opções abaixo:
- [x]  A solução requer alteração pontual no design
- [ ]  A solução requer adaptação de algo existente no design
- [ ]  A solução requer desenho do zero

Escolha uma das opções abaixo:
- [x]  A solução requer alteração pontual no desenvolvimento
- [ ]  A solução requer adaptação de algo existente no desenvolvimento
- [ ]  A solução requer desenvolvimento do zero

Escolha uma das opções abaixo:
- [ ]  A solução envolve apenas o time plataforma
- [x]  A solução envolve outros times de modo pontual, além do time plataforma
- [ ]  A solução envolve outros times de modo mais que pontual, além do time plataforma

**Comment by AldemirLucas** [comment]
em qual local fica essa informação dentro do datasets, em uma bdm_table, external_link? ou a parte?

**Comment by AldemirLucas** [comment]
nessa informação pode vim mais de um link?

**Comment by laura-l-amaral** [comment]
Conversando com o @arthurfg a gente concluiu que tem algumas bases que é muito importante ter arquivos auxiliares, o @rdahis me indicou que já existe um campo para isso, mas precisamos deixar ele visível no front-end quando preenchido, o que não é feito atualmente pq o campo nunca foi preenchido com consistência. Queria começar a fazer isso de subir os arquivos auxiliares, mas é isso precisamos que eles apareçam em front pra que essa ação seja útil

O campo se chama auxiliary_files_url que é para levar pra uma pasta no BQ.
