### ISSUE TITLE
Nova página: Estudos de casos

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#542]
## Contexto

Página central de busca dos estudos de casos

## Tarefas

- [x] Estrutura da página (Figma)
- [ ] Implementar página

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/210405027-0c481ce3-34ce-4f60-882e-5c96869d6bb2.png)

Já está em um bom andamento, darei uma pausa nessa feature para a criação do novo conteúdo da JOTA para uma página de estudos de caso, finalizado esse conteúdo eu volto e finalizo essa feature.
