### ISSUE TITLE
Adaptar site para nova API em GraphQL

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/website#568]

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/214658985-f37ccb33-3d7f-453a-8f38-f357812e7a24.png)

**Comment by AldemirLucas** [comment]
Ja adaptado o chamado do dataset e renderização dos campos : `bdm_tables`, `rawDataSources` e `informationRequests`

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/214945152-2f498ff7-6246-4c12-afcf-2ffc64044ae8.png)

**Comment by AldemirLucas** [comment]
![image](https://user-images.githubusercontent.com/82185307/218179004-eb92dd86-d393-4960-b069-430a8843d4ed.png)

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/224436474-70563460-77bd-49b3-9894-6f3d742a51ff.png)

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/224436514-da3a64f7-a5b3-4a6a-9f00-1bc7971f92db.png)

**Comment by AldemirLucas** [comment]
Por agora retirei o filtro das colunas, estou tentando elaborar uma melhor forma de fazer isso funcionar:
 - Posso filtrar pelo GraphQL, mais toda vez que alguém fazer um filtro  vai fazer um chamado.

**Comment by AldemirLucas** [comment]
![Image](https://user-images.githubusercontent.com/82185307/228048852-e5485a53-529d-4197-a1bd-e761c1bce411.png)

**Comment by mfagundes** [comment]
Dois pontos a serem vistos:
- a autenticação de usuários com o permissionamento (fiz usando as views do próprio Django)
- paginação para o frontend, especialmente na busca (essa talvez seja possível fazer sem passar pelo Django)
