### ISSUE TITLE
Retirar parceria com a Fiquem Sabendo das páginas de Pedido LAI

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#590]
**Problema ou Objetivo**

Hoje toda e qualquer página de pedido LAI na BD aparece como parceria com a Fiquem Sabendo. Isso vem de uma possível parceria no passado que não se materializou. Hoje em dia distorce a informação, porque pedidos lá não tem a ver com a FS.

Logo, podemos tornar essa seção de parceria opcional (como metadado) ou esconder até termos outra solução. Eu prefiro já esconder.

**Informações adicionais**

Exemplo: https://basedosdados.org/dataset/br-cgu-fef?information_request=00075001681201978

**Importância da demanda**
Escolha uma das opções abaixo:
- [x]  Baixa gravidade ou impacto
- [ ]  Média gravidade ou impacto
- [ ]  Alta gravidade ou impacto

**Urgência da demanda**
Escolha uma das opções abaixo:
- [ ]  Pode esperar
- [x]  Merece atenção no curto prazo
- [ ]  Necessita de ação imediata

**Comment by laura-l-amaral** [comment]
@rdahis o metadado se é parceria ou não a principio já existe, pelo menos no site tem um campo para preencher com essa informação

<img width="477" alt="image" src="https://user-images.githubusercontent.com/100051996/231898284-a1e0d0c6-301f-4c99-870f-23044059436e.png">

**Comment by rdahis** [comment]
Estou me referindo ao front-end de parceria com o Fiquem Sabendo. Exemplo: https://basedosdados.org/dataset/br-sgp-informacao?information_request=00137019649202272

Mas de fato, vi que tem outros exemplos onde aparece a parceria sendo a Fundação Lemann, que é o que queremos mesmo (preenchido via metadado).

Outro problema: aqui o metadado tá para o República, mas no FE aparece a Fiquem Sabendo: https://basedosdados.org/dataset/br-me-clima-organizacional?information_request=03005.131729%2F2021-16

**Comment by laura-l-amaral** [comment]
Concluido
