### ISSUE TITLE
Gestão de Secrets

### ISSUE THREAD

**Issue by polvoazul** [basedosdados/website#62]
## Problema:
Hoje os secrets e credenciais estao espalhados em diversos arquivos e lugares: prod_ckan_ini, .env.prod. Senhas de acessos como emails ou acessos pra ferramentas de terceiros estao centralizadas com pessoas especificas (DNS esta com o @rdahis, por exemplo). 
Isso cria bottlenecks e riscos de inconsistencia pois, se alguem precisar atualizar o .env.prod, por exemplo, vai precisar falar com o @polvoazul, ou no minimo, informa-lo de atualizar tambem na sua maquina. 

## Objetivo:
Definir [uma ferramenta/um processo] de gestao de secrets para o basedosdados.

## Requisitos:
1- Barato/Free, considerando um numero de usuarios de approx 10 pessoas.
2- Suporte a secrets de uma linha so (como senhas). Suporte a arquivos (prod_ckan_ini). 
3- Autorizacao flexivel: pessoas diferentes podem ter acessos a grupos de senhas diferentes.
4- Interface humana de facil uso: uma interface grafica tranquila da galera cadastrar e editar secrets
5- Interface programatica: Ex.: o github CI conseguir acessar os secrets necessarios para o deploy diretamente do manager, assim nao corremos risco de inconsistencia.

**Comment by polvoazul** [comment]
Request for comments @rdahis @fernandascovino @JoaoCarabetta @brenodega28 @d116626 @vncsna

**Comment by polvoazul** [comment]
Explorei algumas opcoes:

Solucao | Pros | Contras
--- | --- | ---
Solucao cloud gerenciada https://www.doppler.com/pricing | cumpre todos requisitos muito bem | versao free nao cumpre requisito 3 <br> versao paga custa 6 dolar / mes / user 
Solucao open source https://www.vaultproject.io/docs  | gratis, cumpre tudo | Eh complicado de setupear pois tem mtas features. Tambem tem um custo a mais de manutencao pois a gerencia fica consoco |
Colocar os secrets numa tabela do dynamodb da aws | gratis, simples e cumpre os requisitos | teria q criar users aws pra cada user. Tem q ver se suporta 3.
Colocar os secrets numa tabela do dynamodb da gcp | gratis, simples, todo mundo ja tem uma conta google | Tem q ver se suporta 3. Suporte a arquivos (requisito 2) eh meio zoado.
Secret manager da aws/gcp (KMS) | barato, tem features mais avancadas q no futuro podem ser interessante | um pouco mais complicado do q as tabelas acima.

**Comment by fernandascovino** [comment]
na impulso usávamos o heroku para essa gestão do secrets / deploy Docker no staging, e o digital ocean (se eu nao me engano) para prod... confirmam @JoaoCarabetta @thenets ? talvez seja uma solução mais barata

**Comment by thenets** [comment]
Não cheguei a implementar soluções de secrets. Acredito que uma das maneiras mais baratas seria usar o SOPS (da Mozilla) para criptografia.

Dessa maneira, só precisaria de uma chave pra gerenciar todas as outras. Essa chave pode ser passada por texto plano (usando um canal seguro) ou usar provedores de Cloud.

**Comment by fernandascovino** [comment]
@brenodega28 @d116626 a gente chegou a ver isso ja? prioridade alta?

**Comment by vncsna** [comment]
@fernandascovino não sei como isso se encontra, mas é possível deletar os repositórios vault e secrets por enquanto?

**Comment by fernandascovino** [comment]
boa pergunta @brenodega28 @d116626 pode matar esses repos?

**Comment by guialvesp1** [comment]
Fechando esta tarefa pois o vault já encontra-se em produção como gestor de secrets.
