### ISSUE TITLE
[Design] Criar fluxo de login e cadastro de conta

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#642]
[EQP-15](https://basedosdados.atlassian.net/browse/EQP-15)

[EQP-15]: https://basedosdados.atlassian.net/browse/EQP-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Tarefas**

- [x] Página de cadastro de conta
- [x] Página de confirmação de e-mail para cadastro de conta
- [x] Página de login
- [x] Página de recuperação de senha por link enviado para o e-mail
- [x] E-mail de confirmação de e-mail para cadastro de conta
- [x] E-mail de recuperação de senha por link enviado para o e-mail

**Comment by nayaramrsc** [comment]
**Protótipos**

- [Cadastro](https://www.figma.com/proto/HweLNKqSzabt6EKyTnchm3/basedosdados?type=design&node-id=12793-3678&t=nqrcOuAqVxLlAOHT-0&scaling=scale-down-width&page-id=3524%3A1086&starting-point-node-id=12793%3A3678&show-proto-sidebar=1)

- [Login](https://www.figma.com/proto/HweLNKqSzabt6EKyTnchm3/basedosdados?type=design&node-id=12798-4427&t=nqrcOuAqVxLlAOHT-0&scaling=scale-down-width&page-id=3524%3A1086&starting-point-node-id=12798%3A4427&show-proto-sidebar=1)

**Comment by crislanealves** [comment]
Fechado o processo de design já foi finalizado!
