### ISSUE TITLE
Labels de available_options

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#65]
Agora não está aparecendo em lugar nenhum os labels para chaves de available_options. Qual é a melhor solução pra isso, já vislumbrando suporte multi-língua no futuro?

Ideias:
- Enums aceitarem dicionários, ao invés de chaves.

**Comment by rdahis** [comment]
Exemplo: ver chaves de `spatial_coverage` aqui https://staging.basedosdados.org/api/3/action/package_show?id=br-ibge-populacao

**Comment by d116626** [comment]
https://basedosdados.org/api/3/action/bd_available_options
