### ISSUE TITLE
Atualizar página "Quem Somos"

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/website#684]
- [x] Adicionar novo chamado de usuários(funcionários) pelo GraphQL.
- [x] Consumo das imagens vão ser atribuídas admin Django. 
- [x] Fazer mecanismo de filtro por Times.
- [x] Atualizar as informações das pessoas(funcionários).

**Comment by fernandascovino** [comment]
<img width="594" alt="image" src="https://github.com/basedosdados/website/assets/20743819/f76afaf4-192f-475c-ad04-59ed1d49693d">


@AldemirLucas hotfix, imagem ta quebrada

**Comment by AldemirLucas** [comment]
@fernandascovino não conseguir replicar esse caso, em qual ambiente aconteceu isso?
