### ISSUE TITLE
Adicionar campo `metadata_modified` com subcampo `yaml_order` aos endpoints `bd_bdm_columns_schema` e `bd_dataset_schema`

### ISSUE THREAD

**Issue by vmussa** [basedosdados/website#70]
# Descrição
Para a construção da feature de criação dos metadados via CLI e API em Python, é preciso comparar os arquivos locais do usuário com os dados do CKAN para saber se o usuário está editando um arquivo de metadados atualizado. No entanto, os endpoints do `schema` dos metadados atuais do website não retornam o campo `metadata_modified`, inviabilizando a operação.

# Solução
Para resolver isso, é preciso que os enpoints `bd_dataset_schema` e `bd_bdm_columns_schema` retornem o campo `metadata_modified` com um subcampo `yaml_order` no campo `properties`, para que ele seja incorporado na criação do `YAML` local e, assim, possa acontecer a comparação com os dados do CKAN via `package_show`.

**Comment by rdahis** [comment]
Isso já está feito?
