### ISSUE TITLE
Implementar nova área de usuário

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/website#700]
Link do Jira:[EQP-126]( https://equipeplataforma.atlassian.net/browse/EQP-126)

Design: [Protótipo](https://www.figma.com/proto/HweLNKqSzabt6EKyTnchm3/basedosdados?type=design&node-id=12793-3678&t=nqrcOuAqVxLlAOHT-0&scaling=scale-down-width&page-id=3524%3A1086&starting-point-node-id=12793%3A3678&show-proto-sidebar=1)

[EQP-126]: https://equipeplataforma.atlassian.net/browse/EQP-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AldemirLucas** [comment]
6/10 update, page in WIP

![image](https://github.com/basedosdados/website/assets/82185307/00b22a5e-471c-459f-966f-6f47a8e2219a)

**Comment by AldemirLucas** [comment]
![image](https://github.com/basedosdados/website/assets/82185307/a9634634-9fc9-4f2d-93f3-8d7116bb9fe2)

![image](https://github.com/basedosdados/website/assets/82185307/b761a73c-d3fa-4845-9914-103c16caca0e)

![image](https://github.com/basedosdados/website/assets/82185307/1119897a-d863-4c0f-be0f-e95db004390b)

![image](https://github.com/basedosdados/website/assets/82185307/00e5f0a1-653e-4156-af2f-e946b685dc18)

![image](https://github.com/basedosdados/website/assets/82185307/891adc7d-611a-42d4-a030-ec65b4e0485f)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/5138d411-8a28-42ec-b19c-fd3bbb14672a)

**Comment by AldemirLucas** [comment]
Reenvio de email funcional

![Image](https://github.com/basedosdados/website/assets/82185307/ecc23c85-3b54-41e2-89cc-52fdb9e18e86)
