### ISSUE TITLE
Corrigir issues gerais

### ISSUE THREAD

**Issue by vncsna** [basedosdados/website#71]
- [ ] Dar uma limpa nas extensões, fixar versões e aplicar vendoring;
- [ ] Organizar configurações de prod/dev, adicionando o possível no docker-compose;
- [ ] Adicionar ckan e extensões como subtree do repositório;
- [ ] Organizar testes;
- [ ] Remover histórico do git (postgres-prod-dump.custom, initdbs);
- [ ] Checar as views do site (parece quebrado).

Via comentários do Fred em arquivos diversos

**Comment by fernandascovino** [comment]
@vncsna ainda se aplica ou pode fechar?

**Comment by vncsna** [comment]
Acho que pode fechar
