### ISSUE TITLE
Alterar exibição de cobertura temporal de trimestre

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/website#722]
Proposta: Mudar de para `YYYY-QX`

Exemplo: 

Na PNADc em https://basedosdados.org/dataset/9fa532fb-5681-4903-b99d-01dc45fd527a.

Tá aparecendo como se fosse mês `2012-01 ─ 2023-02` mas deve ser `2012-Q1 ─ 2023-Q2`

**Comment by laura-l-amaral** [comment]
Foi ajustado alterando a informação de date-time-range inteira para mês. Agora está 2021-03 - 2023-06
