### ISSUE TITLE
Adicionar o stripe no front-end

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/website#724]
https://github.com/basedosdados/website/tree/feat/stripe

**Comment by AldemirLucas** [comment]
![image](https://github.com/basedosdados/website/assets/82185307/a4e8cfdf-9455-474f-a26c-e3d213a98c1d)

**Comment by AldemirLucas** [comment]
status de pagamento confirmando e implementação funcionando como esperado.

![image](https://github.com/basedosdados/website/assets/82185307/ddc2cb82-2700-4b93-9c85-d0990fa6bbfb)

![image](https://github.com/basedosdados/website/assets/82185307/6e0968ea-471f-4f59-9aee-691b65118075)
