### ISSUE TITLE
[develop] `package_validate` não levanta exceção em caso de erro de validação

### ISSUE THREAD

**Issue by vmussa** [basedosdados/website#75]
# Descrição

Quando há não há sucesso na validação dos metadados, o endpoint `package_validate` não levanta a exceção `ValidationError`, embora ela seja definida no início do código:
https://github.com/basedosdados/website/blob/c7f65eb6ce6d0a6804ee087a3304632f6d911357/ckanext-basedosdados/ckanext/basedosdados/actions/__init__.py#L9

# Comportamento esperado

Talvez o levantamento da exceção seja mais interessante para o uso do `package_validate` pelo cliente Python/CLI `basedosdados`, para não termos que parsear o resultado do endpoint e, possivelmente, quebrar o código com alguma mudança futura na estrutura da resposta da API, embora isso não seja tão provável, por ser uma resposta simples.

**Comment by vncsna** [comment]
@vmussa esse problema ainda é válido? Hoje o `bd_dataset_validate` (antigo `package_validate`) retorna um json com um campo `errors`. Não entendi ao certo o que uma exceção no servidor serviria para o cliente.

**Comment by vmussa** [comment]
@vncsna, pelo que estou entendendo, as exceções levantadas no servidor são acessíveis no cliente também ao importar o `ckanapi` e/ou usar o `RemoteCKAN`, pelo menos o código antigo dos metadados indicava isso (@JoaoCarabetta me corrija se estiver errado). Mas eu tb acho que é suficiente esse campo `errors` do JSON de resposta. Levantei essa Issue mais pq tinha uma `ValidationError` sendo importada sem uso e sendo chamada do lado do cliente, então pensei que pudesse ter sido não proposital. Por mim, a forma atual já está ótima!
