### ISSUE TITLE
Criar pontos de espera na área do usuário

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#767]

**Comment by rdahis** [comment]
Para eu acompanhar assíncrono, podem por favor listar na descrição da issue quais pontos exatamente são esses? Eu pergunto porque tem vários pontos onde falta espera que me incomodam no site e queria checar que estão cobertos aqui. Valeu.

**Comment by AldemirLucas** [comment]
Foi aplicador pontos de esperas:
- Área Perfil público:
 - Atualização do perfil
 - Remoção da imagem
 - Atualização da imagem
- Área Conta:
 - Alterar nome de usuário
 - Apagar conta
- Área Senha:
 - Alterar senha
- Área Planos e Pagamentos:
 - Assinar ou Cancelar o plano

**Comment by rdahis** [comment]
Conseguimos adicionar uma espera na busca para evitar isso aqui?
![Screenshot 2024-04-23 at 23 08 48](https://github.com/basedosdados/website/assets/6617207/ab5af4aa-16e5-4954-ac5e-a873e5171f1a)

**Comment by AldemirLucas** [comment]
conseguimos, tem mais algum lugar para adicionar?

**Comment by rdahis** [comment]
Boa. Tem essa mesma questão no carrossel na home. Mas acho que por enquanto é isso.
