### ISSUE TITLE
Deploy do website não está funcionando!

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/website#77]
URGENTE:
- [x] Resolver `deploy`, está quebrado desde que lançamos? https://github.com/basedosdados/website/deployments/activity_log
- [x] Bootstrap local também não funciona
  - [x] Não fechar o terminal quando não roda o código (remover `exit code 1` para outra coisa menos agressiva), senão não da para ler os erros nem logs

Outros:
- [x] #239

**Comment by fernandascovino** [comment]
@brenodega28 qual. nivel de prioridade?
