### ISSUE TITLE
Protótipo de alta fidelidade do cruzamento de tabelas

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#788]
[Protótipos](https://www.figma.com/design/HweLNKqSzabt6EKyTnchm3/Plataforma?node-id=1115-0&t=HhxKohkIQydvrFLj-0)

**Comment by laura-l-amaral** [comment]
reorganizamos a feature separando os diferentes problemas do usuário https://coda.io/d/Plataforma_dkbq8r9l4IO/Cruzamento-de-Tabelas_suCAU#_lucMC
