### ISSUE TITLE
Remover parceria com fiquem sabendo de todos os pedidos LAIs

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#801]
Atualmente todas os pedidos LAI estão com essa tag da Fiquem Sabendo sendo que muitos desses pedidos não tem nada a ver com eles. Tem que tirar esse aviso de parceria 

link para exemplo: https://basedosdados.org/dataset/dae21af4-4b6a-42f4-b94a-4c2061ea9de5?information_request=ef9ae097-fba8-4cc4-acb2-8867990452d0

![Image](https://github.com/basedosdados/website/assets/100051996/392d0cd0-3847-4b4c-af5c-4cc6acec67da)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/681cf6dc-9c57-4e65-a152-58112e501780)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/3140144b-066e-41d5-b003-eac0e49cb54c)
