### ISSUE TITLE
ações sobre a página de BD Lab.

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#822]
1. Tirar topo da página “BD Pro” e colocar “BD Lab” com uma frase.
  2. Passar os estudos de caso para essa dentro dessa página.
  3. Mudar o item no menu para BD Lab.
  4. Remover Imagens e Gráficos
  5. Ajustar fonte

**Comment by AldemirLucas** [comment]
Faltando troca a Logo:

![Image](https://github.com/basedosdados/website/assets/82185307/41984906-a71f-4e00-8ee5-1b8517f02d98)

**Comment by AldemirLucas** [comment]
está ficando assim o corpo das informações:

![Image](https://github.com/basedosdados/website/assets/82185307/ec0d40d3-2678-4ea5-82da-a176552342b4)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/7a7527e0-3781-4bf6-9a58-a2a73c096cc2)

**Comment by laura-l-amaral** [comment]
> ![Image](https://private-user-images.githubusercontent.com/82185307/329386425-7a7527e0-3781-4bf6-9a58-a2a73c096cc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyOTI3NTIsIm5iZiI6MTcxNTI5MjQ1MiwicGF0aCI6Ii84MjE4NTMwNy8zMjkzODY0MjUtN2E3NTI3ZTAtMzc4MS00YmY2LTlhNTgtYTJhNzNjMDk2Y2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDIyMDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTUyMDUwMTgyMTlkNGE3Zjk0Y2Y2MTM1MTQ2MGEzYWNhZDI0N2Y1MjY0ODQ1Y2ZlYzMyNTAyNTIyNTIzMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvZvREHo8FFfWQLHnjCurj5QQmpCB_mFev7cxGAyg1c)

pq tirou a caixinha e o sistema de clicar para aparecer?
