### ISSUE TITLE
Criar versão anual com desconto dos planos - Construir Front

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#833]
Questões de negócio:
* O que fazer com a pessoa quando ela faz upgrade? -> consideramos que não é necessario
* BDpro e BD Empresas anual?

* Incluir também mudança do texto de assinatura caso o usuário já tenha utilizado o teste grátis

**Comment by laura-l-amaral** [comment]
Atualmente não é possível fazer o pagamento do plano empresas. Existe um problema no endpoint que precisa ser resolvido pelo back.

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/a1d0d481-368a-497b-9d81-fd39639b81ad)

Precisa ser adicionado no allStripePrice para o stripe coletar como uma forma de pagamento
