### ISSUE TITLE
Pequenos ajustes no front

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#837]
Ajuste em quem somos - Fazer aparecer a categoria de BDEdu
Ajuste no link do menu suspenso de BDedu para - https://info.basedosdados.org/bd-edu-sql

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/0c67f0f4-bf4d-400a-83fc-85d4b62aa589)
