### ISSUE TITLE
Tradução de Tabelas - Página de Conjunto

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#857]
[Protótipos](https://www.figma.com/design/HweLNKqSzabt6EKyTnchm3/Plataforma?node-id=15751-11596&t=xsWwqQZSAp84G1pJ-0)

getTableOneBigTableQuery

---

- [x] Incluir bloqueio para tabela do SAEB (faltando o texto para disclaimer)
- [x] SAEB disponibilizar a visualização do dicionario nas tabelas tratadas
- [x] Incluir 'Sem previsão de atualização' para tabelas sem o metadado de update
- [x] Levar consulta entre linguagens
- [x] Ajustar a barrinha da seleção de linguagem
- [x] Colocar perguntinha no header
- [x] trocar "Fazer download da tabela que faz a tradução desta coluna" -> "Baixar tabela que faz a tradução desta coluna"
- [x] Atualizar botão 'entrar/cadastrar'
- [x] Ajustar fonte no Menu para Roboto
- [x] Link par o "limite de processamento gratuito"
- [x] Checkbox logica de seleção
- [x] Adicionar campo ID para o BigQuery

Busca
- [x] Diminuir espaçamento entre itens da coluna filtro na página 

Nay:
- [x] Explicar separação entre marketing e produto (footer e fonte)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/4358c0ea-7729-4ecb-a8f2-412378dddcac)

**Comment by AldemirLucas** [comment]
@laura-l-amaral 

Existe já essa coleta do tamanho da tabela? 

![Image](https://github.com/basedosdados/website/assets/82185307/452f3a3f-1539-41c1-a9a3-a83fe9dd3b5b)

**Comment by laura-l-amaral** [comment]
já! uncompressedFileSize

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/0c8d53f3-ef20-4b1b-a556-d1712169b621)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/071e55e4-b65e-4b61-be43-559b07b9521f)

**Comment by AldemirLucas** [comment]
Atualização de "Frequência de atualização dos dados" e "Fontes originais"

info coletadas de PROD, dataset:"782c5607-9f69-4e12-b0d5-aa0f1a7a94e2", table:"28d16282-d100-4ea8-9dde-36c05c8f1ca2"

![Image](https://github.com/basedosdados/website/assets/82185307/47302eec-fddc-4f37-96e5-84494de48384)

Fiz um formatador de texto para cada tipo de atualização disponíveis nas Entitys

![Image](https://github.com/basedosdados/website/assets/82185307/a88498c9-36e9-4712-92d4-57f4ed976be6)

**Comment by AldemirLucas** [comment]
A tabela de dados já está no novo padrão, faltando apenas criar as checkbox's e o filtro de coluna,

![Image](https://github.com/basedosdados/website/assets/82185307/7f507ebc-8e9c-4ade-b78b-bb27e0811dd7)

E na área de download fazer essa variação da "Precisa de tradução" para "Tabela de tradução":

![Image](https://github.com/basedosdados/website/assets/82185307/4dc5e508-9f0f-4730-a616-c4c905e7a19a)

**Comment by laura-l-amaral** [comment]
- [ ] Nivel de observação
- [ ] FAQ
- [ ] Pedidos LAI (ajustes de texto)
- [ ] Fontes Originais (ajustes de texto)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/6b8c4df9-4217-4d18-ab02-a8ea53acf964)



![Image](https://github.com/basedosdados/website/assets/82185307/ee47aa9f-1d62-4261-b346-2fb1def46700)

**Comment by nayaramrsc** [comment]
- [ ] descrições de recursos com muito espaço
- [ ] disclaimer sobre processamento
- [ ] link de acessar o bigquery personalizado com o dataset (referência a prod)
- [ ] download 
  - [ ] alterar texto para "Não precisa de tradução"
  - [ ] exibir nome das tabelas de tradução
  - [ ] exibir link que faz o download das tabelas de tradução
  - [ ] corrigir "linhas"
- [ ] tirar a exibição das tabelas de dicionário dos conjuntos (slug `dicionario` ou `dictionary`)
- [ ] frequência de atualização da atualização na fonte original

**Comment by laura-l-amaral** [comment]
- [ ] Incluir bloqueio para tabela do SAEB

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/fd98098b-4291-4b23-88fe-2d7a966a69ca)
