### ISSUE TITLE
[website] Documentação da API

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/website#86]
- [ ] Adicionar link da documentação da API na documentação central da Base dos Dados
- [ ] ~~Mudar nome da url de `openapi` para `docs-api`~~
- [x] Trocar a ordem dos servidores para `basedosdados` --> develop --> localhost

**Comment by d116626** [comment]
- [ ] Adicionar `package_update`e outros endpoints como `package_patch` da [api](https://docs.ckan.org/en/2.9/api/) do CKAN  
- [ ] Adicionar os demais schemas ou endpoints do tipo `bd_*` do [`get.py`](https://github.com/basedosdados/website/blob/develop/ckanext-basedosdados/ckanext/basedosdados/actions/get.py)

**Comment by vncsna** [comment]
Eu prefiro que fique openapi, acho que é mais descritivo sobre a ferramenta. E não é nada complexo, só decorar o nome.
