### ISSUE TITLE
Tradução de Tabelas - Página de Busca

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#870]
- [x] Filtros
- [x] Personalização dos Cards
- [x] Search
- [x] Tags das pesquisas
- [x] Bug na tag da página de consulta

**Comment by AldemirLucas** [comment]
Funcionando como o esperado já.

![Image](https://github.com/basedosdados/website/assets/82185307/c12ff840-b2c5-4237-bab0-7dabd97c3a47)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/071e36d1-573d-4a80-bafe-3ab2f13eb35c)

![Image](https://github.com/basedosdados/website/assets/82185307/e648b220-c79f-4e16-8a95-a0cdba3adf75)

**Comment by AldemirLucas** [comment]
![Image](https://github.com/basedosdados/website/assets/82185307/94943731-a55d-4e1f-bca8-1185f9087992)
