### ISSUE TITLE
Adicionar logo atual no CKAN.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/website#9]
O arquivo já está em `website/ckanext-basedosdados/ckanext/basedosdados/public/images/bd_logo_horizontal.png`.

Falta fazer aparecer na home.

**Comment by fernandascovino** [comment]
quem faz isso é o admin, não é no código

**Comment by rdahis** [comment]
Verdade. Mudei lá. O alinhamento tá esquisito ainda mas vou fechar a issue.
