### ISSUE TITLE
Mostrar até quando o plano fica ativo

### ISSUE THREAD

**Issue by nayaramrsc** [basedosdados/website#902]
[Protótipos](https://www.figma.com/design/HweLNKqSzabt6EKyTnchm3/Plataforma?node-id=18303-7268&t=8z6nO6Xi1w1VrysZ-0)
 
![Image](https://github.com/user-attachments/assets/d8a8dbd5-d420-4611-b4c2-0c13d31a4880)
Adicionar no intenalSubscription: @jhonylucas74 
- se o plano é anual ou mensal
- próxima cobrança no cartão
- data de até quando o plano ficara ativo depois do cancelamento

- [x] Incluir texto pedindo para pessoa enviar um e-mail para equipe da BD fazer o upgrade do plano

**Comment by jhony-spocket** [comment]
Alterações feitas, disponíveis em dev no momento.
