### ISSUE TITLE
Implementar Cupom

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#909]
- [x] começar com integração com back
- [x] implementar [design](https://www.figma.com/design/HweLNKqSzabt6EKyTnchm3/Plataforma?node-id=18564-14344) da nay
- [x] personalização do stripe

**Comment by AldemirLucas** [comment]
![Image](https://github.com/user-attachments/assets/c743e5d4-1fa5-4da9-be26-4e54ab8a6fc4)
