### ISSUE TITLE
Investigar problemas no stripe em prod no ambiente de teste

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#940]

**Comment by laura-l-amaral** [comment]
@AldemirLucas coloca algum resumo do que vc fez e concluiu aqui

**Comment by AldemirLucas** [comment]
O problema reportado era que o modal de pagamento do stripe não abria se usasse o ambiente do backend de Prod.

O clientscret do ambiente de Prod não é criado nos "testes" do stripe por isso ele não consegue abrir o modal de pagamento se usado em ambiente de teste, é um comportamento correto a se esperar e não um bug.
