### ISSUE TITLE
Pensar sobre hacktoberfest

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/website#949]
Para Blog
- [ ] Escolher os datasets (10)
- [ ] Fazer o modelo
- [ ] Deixar avisado na issue para fazer o fork na branch e não na main
- [ ] Montar uma issue para cada dataset
- [ ] Colocar a tag `hacktoberfest2024`

**Comment by Siddharthgup** [comment]
Hi @laura-l-amaral ,Can you assign this taskk to me ?

**Comment by Siddharthgup** [comment]
Yes,  not fluently but understand
