### ISSUE TITLE
Corrigir circular imports das bibliotecas

### ISSUE THREAD

**Issue by vncsna** [basedosdados/website#98]
E depois disso alterar a parte do `isort` da action de continuous integration de  

`python -m isort --check-only --profile black --skip __init__.py --skip vendor .`

para  

`python -m isort --check-only --profile black  --skip vendor .`

**Comment by fernandascovino** [comment]
@vncsna ainda se aplica? qual a prioridade?

**Comment by vncsna** [comment]
Não muita, vou fechar também
